<?php
/**
 * ACF field registration for Mohcine content.
 */

function astra_mohcine_register_acf_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	$page_id = astra_mohcine_settings_page_id();
	if ( ! $page_id ) {
		return;
	}

	acf_add_local_field_group(
		array(
			'key'      => 'group_Mohcine_settings',
			'title'    => 'Mohcine Settings',
			'fields'   => array(
				array(
					'key'        => 'field_topbar_group',
					'label'      => 'الشريط العلوي',
					'name'       => 'topbar_group',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'   => 'field_topbar_phone',
							'label' => 'رقم الهاتف',
							'name'  => 'topbar_phone',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_topbar_email',
							'label' => 'البريد الإلكتروني',
							'name'  => 'topbar_email',
							'type'  => 'email',
						),
						array(
							'key'   => 'field_topbar_cta_text',
							'label' => 'نص الزر',
							'name'  => 'topbar_cta_text',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_topbar_cta_link',
							'label' => 'رابط الزر',
							'name'  => 'topbar_cta_link',
							'type'  => 'text',
						),
					),
				),
				array(
					'key'        => 'field_hero_slides',
					'label'      => 'شرائح البطل (العناوين فقط)',
					'name'       => 'hero_slides',
					'type'       => 'group',
					'layout'     => 'row',
					'sub_fields' => array(
						array(
							'key'   => 'field_hero_slide_1',
							'label' => 'شريحة 1',
							'name'  => 'hero_slide_1_title',
							'type'  => 'text',
						),
						array(
							'key'            => 'field_hero_slide_1_image',
							'label'          => 'صورة 1',
							'name'           => 'hero_slide_1_image',
							'type'           => 'image',
							'return_format'  => 'url',
							'preview_size'   => 'medium',
							'library'        => 'all',
						),
						array(
							'key'   => 'field_hero_slide_2',
							'label' => 'شريحة 2',
							'name'  => 'hero_slide_2_title',
							'type'  => 'text',
						),
						array(
							'key'            => 'field_hero_slide_2_image',
							'label'          => 'صورة 2',
							'name'           => 'hero_slide_2_image',
							'type'           => 'image',
							'return_format'  => 'url',
							'preview_size'   => 'medium',
							'library'        => 'all',
						),
						array(
							'key'   => 'field_hero_slide_3',
							'label' => 'شريحة 3',
							'name'  => 'hero_slide_3_title',
							'type'  => 'text',
						),
						array(
							'key'            => 'field_hero_slide_3_image',
							'label'          => 'صورة 3',
							'name'           => 'hero_slide_3_image',
							'type'           => 'image',
							'return_format'  => 'url',
							'preview_size'   => 'medium',
							'library'        => 'all',
						),
						array(
							'key'   => 'field_hero_slide_4',
							'label' => 'شريحة 4',
							'name'  => 'hero_slide_4_title',
							'type'  => 'text',
						),
						array(
							'key'            => 'field_hero_slide_4_image',
							'label'          => 'صورة 4',
							'name'           => 'hero_slide_4_image',
							'type'           => 'image',
							'return_format'  => 'url',
							'preview_size'   => 'medium',
							'library'        => 'all',
						),
					),
				),
			array(
				'key'        => 'field_footer_group',
				'label'      => 'تذييل الموقع',
				'name'       => 'footer_group',
				'type'       => 'group',
				'sub_fields' => array(
					array(
						'key'   => 'field_footer_logo_title',
						'label' => 'عنوان الشعار',
						'name'  => 'logo_title',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_logo_subtitle',
						'label' => 'وصف الشعار',
						'name'  => 'logo_subtitle',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_description',
						'label' => 'الوصف',
						'name'  => 'description',
						'type'  => 'textarea',
					),
					array(
						'key'   => 'field_footer_copyright',
						'label' => 'حقوق النشر',
						'name'  => 'copyright',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_address',
						'label' => 'العنوان',
						'name'  => 'address',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_phone',
						'label' => 'الهاتف',
						'name'  => 'phone',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_email',
						'label' => 'البريد الإلكتروني',
						'name'  => 'email',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_hours',
						'label' => 'أوقات العمل',
						'name'  => 'hours',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_hosting_note',
						'label' => 'ملاحظة الاستضافة',
						'name'  => 'hosting_note',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_hosting_url',
						'label' => 'رابط الاستضافة',
						'name'  => 'hosting_url',
						'type'  => 'url',
					),
					array(
						'key'   => 'field_footer_newsletter_text',
						'label' => 'نص النشرة البريدية',
						'name'  => 'newsletter_text',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_newsletter_placeholder',
						'label' => 'النشرة البريدية - العنونة',
						'name'  => 'newsletter_placeholder',
						'type'  => 'text',
					),
					array(
						'key'   => 'field_footer_whatsapp',
						'label' => 'رابط واتساب',
						'name'  => 'whatsapp_link',
						'type'  => 'url',
					),
					array(
						'key'   => 'field_footer_instagram',
						'label' => 'رابط انستقرام',
						'name'  => 'instagram_link',
						'type'  => 'url',
					),
					array(
						'key'   => 'field_footer_facebook',
						'label' => 'رابط فيسبوك',
						'name'  => 'facebook_link',
						'type'  => 'url',
					),
					array(
						'key'   => 'field_footer_youtube',
						'label' => 'رابط يوتيوب',
						'name'  => 'youtube_link',
						'type'  => 'url',
					),
					array(
						'key'   => 'field_footer_tiktok',
						'label' => 'رابط تيك توك',
						'name'  => 'tiktok_link',
						'type'  => 'url',
					),
				),
			),
				array(
					'key'        => 'field_services',
					'label'      => 'الخدمات (ثابتة ٣)',
					'name'       => 'services',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'        => 'field_service_1',
							'label'      => 'خدمة 1',
							'name'       => 'service_1',
							'type'       => 'group',
							'sub_fields' => array(
								array(
									'key'   => 'field_service_1_title',
									'label' => 'العنوان',
									'name'  => 'service_1_title',
									'type'  => 'text',
								),
								array(
									'key'   => 'field_service_1_description',
									'label' => 'الوصف',
									'name'  => 'service_1_description',
									'type'  => 'textarea',
								),
								array(
									'key'   => 'field_service_1_cta',
									'label' => 'نص الزر',
									'name'  => 'service_1_cta',
									'type'  => 'text',
								),
							),
						),
						array(
							'key'        => 'field_service_2',
							'label'      => 'خدمة 2',
							'name'       => 'service_2',
							'type'       => 'group',
							'sub_fields' => array(
								array(
									'key'   => 'field_service_2_title',
									'label' => 'العنوان',
									'name'  => 'service_2_title',
									'type'  => 'text',
								),
								array(
									'key'   => 'field_service_2_description',
									'label' => 'الوصف',
									'name'  => 'service_2_description',
									'type'  => 'textarea',
								),
								array(
									'key'   => 'field_service_2_cta',
									'label' => 'نص الزر',
									'name'  => 'service_2_cta',
									'type'  => 'text',
								),
							),
						),
						array(
							'key'        => 'field_service_3',
							'label'      => 'خدمة 3',
							'name'       => 'service_3',
							'type'       => 'group',
							'sub_fields' => array(
								array(
									'key'   => 'field_service_3_title',
									'label' => 'العنوان',
									'name'  => 'service_3_title',
									'type'  => 'text',
								),
								array(
									'key'   => 'field_service_3_description',
									'label' => 'الوصف',
									'name'  => 'service_3_description',
									'type'  => 'textarea',
								),
								array(
									'key'   => 'field_service_3_cta',
									'label' => 'نص الزر',
									'name'  => 'service_3_cta',
									'type'  => 'text',
								),
							),
						),
					),
				),
				array(
					'key'        => 'field_cta_group',
					'label'      => 'دعوة للعمل',
					'name'       => 'cta_group',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'   => 'field_cta_title',
							'label' => 'العنوان',
							'name'  => 'cta_title',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_cta_description',
							'label' => 'الوصف',
							'name'  => 'cta_description',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_cta_button_text',
							'label' => 'نص الزر',
							'name'  => 'cta_button_text',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_cta_button_link',
							'label' => 'رابط الزر',
							'name'  => 'cta_button_link',
							'type'  => 'text',
						),
					),
				),
				array(
					'key'        => 'field_contact_group',
					'label'      => 'التواصل',
					'name'       => 'contact_group',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'   => 'field_contact_address',
							'label' => 'العنوان',
							'name'  => 'contact_address',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_contact_phone',
							'label' => 'الهاتف',
							'name'  => 'contact_phone',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_contact_email',
							'label' => 'البريد الإلكتروني',
							'name'  => 'contact_email',
							'type'  => 'email',
						),
						array(
							'key'   => 'field_contact_hours',
							'label' => 'أوقات العمل',
							'name'  => 'contact_hours',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_contact_map_embed',
							'label' => 'تضمين الخريطة',
							'name'  => 'contact_map_embed',
							'type'  => 'textarea',
						),
					),
				),
				array(
					'key'        => 'field_whatsapp_group',
					'label'      => 'زر واتساب',
					'name'       => 'whatsapp_group',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'   => 'field_whatsapp_phone',
							'label' => 'رقم واتساب (بدون +)',
							'name'  => 'whatsapp_phone',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_whatsapp_message',
							'label' => 'الرسالة الافتراضية',
							'name'  => 'whatsapp_message',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_whatsapp_label',
							'label' => 'نص الزر',
							'name'  => 'whatsapp_label',
							'type'  => 'text',
						),
					),
				),
				array(
					'key'        => 'field_stats_group',
					'label'      => 'الإحصاءات',
					'name'       => 'stats_group',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'   => 'field_stat_1_value',
							'label' => 'القيمة 1',
							'name'  => 'stat_1_value',
							'type'  => 'number',
						),
						array(
							'key'   => 'field_stat_2_value',
							'label' => 'القيمة 2',
							'name'  => 'stat_2_value',
							'type'  => 'number',
						),
						array(
							'key'   => 'field_stat_3_value',
							'label' => 'القيمة 3',
							'name'  => 'stat_3_value',
							'type'  => 'number',
						),
						array(
							'key'   => 'field_stat_4_value',
							'label' => 'القيمة 4',
							'name'  => 'stat_4_value',
							'type'  => 'number',
						),
					),
				),
				array(
					'key'        => 'field_chairman_group',
					'label'      => 'كلمة رئيس مجلس الإدارة',
					'name'       => 'chairman_group',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'   => 'field_chairman_title',
							'label' => 'العنوان',
							'name'  => 'chairman_title',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_chairman_intro',
							'label' => 'مقدمة',
							'name'  => 'chairman_intro',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_chairman_para1',
							'label' => 'فقرة 1',
							'name'  => 'chairman_para1',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_chairman_para2',
							'label' => 'فقرة 2',
							'name'  => 'chairman_para2',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_chairman_para3',
							'label' => 'فقرة 3',
							'name'  => 'chairman_para3',
							'type'  => 'textarea',
						),
				array(
					'key'   => 'field_chairman_signoff',
					'label' => '???? ???????',
					'name'  => 'chairman_signoff',
					'type'  => 'text',
				),
						array(
							'key'   => 'field_chairman_name',
							'label' => 'الاسم',
							'name'  => 'chairman_name',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_chairman_role',
							'label' => 'الصفة',
							'name'  => 'chairman_role',
							'type'  => 'text',
						),
					),
				),
				array(
					'key'        => 'field_about_group',
					'label'      => 'عن الجمعية',
					'name'       => 'about_group',
					'type'       => 'group',
					'sub_fields' => array(
						array(
							'key'   => 'field_about_origin',
							'label' => 'نص النشأة',
							'name'  => 'about_origin',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_about_vision',
							'label' => 'نص الرؤية',
							'name'  => 'about_vision',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_about_mission',
							'label' => 'نص الرسالة',
							'name'  => 'about_mission',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_goal_1',
							'label' => 'هدف 1',
							'name'  => 'goal_1',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_goal_2',
							'label' => 'هدف 2',
							'name'  => 'goal_2',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_goal_3',
							'label' => 'هدف 3',
							'name'  => 'goal_3',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_goal_4',
							'label' => 'هدف 4',
							'name'  => 'goal_4',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_goal_5',
							'label' => 'هدف 5',
							'name'  => 'goal_5',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_goal_6',
							'label' => 'هدف 6',
							'name'  => 'goal_6',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_1_year',
							'label' => 'التسلسل 1 السنة',
							'name'  => 'timeline_1_year',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_1_title',
							'label' => 'التسلسل 1 العنوان',
							'name'  => 'timeline_1_title',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_1_desc',
							'label' => 'التسلسل 1 الوصف',
							'name'  => 'timeline_1_desc',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_timeline_2_year',
							'label' => 'التسلسل 2 السنة',
							'name'  => 'timeline_2_year',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_2_title',
							'label' => 'التسلسل 2 العنوان',
							'name'  => 'timeline_2_title',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_2_desc',
							'label' => 'التسلسل 2 الوصف',
							'name'  => 'timeline_2_desc',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_timeline_3_year',
							'label' => 'التسلسل 3 السنة',
							'name'  => 'timeline_3_year',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_3_title',
							'label' => 'التسلسل 3 العنوان',
							'name'  => 'timeline_3_title',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_3_desc',
							'label' => 'التسلسل 3 الوصف',
							'name'  => 'timeline_3_desc',
							'type'  => 'textarea',
						),
						array(
							'key'   => 'field_timeline_4_year',
							'label' => 'التسلسل 4 السنة',
							'name'  => 'timeline_4_year',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_4_title',
							'label' => 'التسلسل 4 العنوان',
							'name'  => 'timeline_4_title',
							'type'  => 'text',
						),
						array(
							'key'   => 'field_timeline_4_desc',
							'label' => 'التسلسل 4 الوصف',
							'name'  => 'timeline_4_desc',
							'type'  => 'textarea',
						),
					),
				),
				array(
					'key'        => 'field_programs_group',
				'label'      => 'البرامج (6 ثابتة)',
				'name'       => 'programs_group',
				'type'       => 'group',
				'sub_fields' => array(
					array(
						'key'   => 'field_program_1',
						'label' => '?????? 1',
						'name'  => 'program_1',
						'type'  => 'group',
						'sub_fields' => array(
							array(
								'key'   => 'field_program_1_title',
								'label' => '???????',
								'name'  => 'program_1_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_1_description',
								'label' => '?????',
								'name'  => 'program_1_description',
								'type'  => 'textarea',
							),
							array(
								'key'   => 'field_program_1_beneficiaries',
								'label' => '??????????',
								'name'  => 'program_1_beneficiaries',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_1_duration',
								'label' => '?????',
								'name'  => 'program_1_duration',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_1_location',
								'label' => '??????',
								'name'  => 'program_1_location',
								'type'  => 'text',
							),
							array(
								'key'            => 'field_program_1_image',
								'label'          => 'صورة البرنامج',
								'name'           => 'program_1_image',
								'type'           => 'image',
								'return_format'  => 'url',
								'preview_size'   => 'medium',
								'library'        => 'all',
							),
							array(
								'key'   => 'field_program_1_objective_1',
								'label' => '??? 1',
								'name'  => 'program_1_objective_1',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_1_objective_2',
								'label' => '??? 2',
								'name'  => 'program_1_objective_2',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_1_objective_3',
								'label' => '??? 3',
								'name'  => 'program_1_objective_3',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_1_objective_4',
								'label' => '??? 4',
								'name'  => 'program_1_objective_4',
								'type'  => 'text',
							),
						),
					),
					array(
						'key'   => 'field_program_2',
						'label' => '?????? 2',
						'name'  => 'program_2',
						'type'  => 'group',
						'sub_fields' => array(
							array(
								'key'   => 'field_program_2_title',
								'label' => '???????',
								'name'  => 'program_2_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_2_description',
								'label' => '?????',
								'name'  => 'program_2_description',
								'type'  => 'textarea',
							),
							array(
								'key'   => 'field_program_2_beneficiaries',
								'label' => '??????????',
								'name'  => 'program_2_beneficiaries',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_2_duration',
								'label' => '?????',
								'name'  => 'program_2_duration',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_2_location',
								'label' => '??????',
								'name'  => 'program_2_location',
								'type'  => 'text',
							),
							array(
								'key'            => 'field_program_2_image',
								'label'          => 'صورة البرنامج',
								'name'           => 'program_2_image',
								'type'           => 'image',
								'return_format'  => 'url',
								'preview_size'   => 'medium',
								'library'        => 'all',
							),
							array(
								'key'   => 'field_program_2_objective_1',
								'label' => '??? 1',
								'name'  => 'program_2_objective_1',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_2_objective_2',
								'label' => '??? 2',
								'name'  => 'program_2_objective_2',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_2_objective_3',
								'label' => '??? 3',
								'name'  => 'program_2_objective_3',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_2_objective_4',
								'label' => '??? 4',
								'name'  => 'program_2_objective_4',
								'type'  => 'text',
							),
						),
					),
					array(
						'key'   => 'field_program_3',
						'label' => '?????? 3',
						'name'  => 'program_3',
						'type'  => 'group',
						'sub_fields' => array(
							array(
								'key'   => 'field_program_3_title',
								'label' => '???????',
								'name'  => 'program_3_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_3_description',
								'label' => '?????',
								'name'  => 'program_3_description',
								'type'  => 'textarea',
							),
							array(
								'key'   => 'field_program_3_beneficiaries',
								'label' => '??????????',
								'name'  => 'program_3_beneficiaries',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_3_duration',
								'label' => '?????',
								'name'  => 'program_3_duration',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_3_location',
								'label' => '??????',
								'name'  => 'program_3_location',
								'type'  => 'text',
							),
							array(
								'key'            => 'field_program_3_image',
								'label'          => 'صورة البرنامج',
								'name'           => 'program_3_image',
								'type'           => 'image',
								'return_format'  => 'url',
								'preview_size'   => 'medium',
								'library'        => 'all',
							),
							array(
								'key'   => 'field_program_3_objective_1',
								'label' => '??? 1',
								'name'  => 'program_3_objective_1',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_3_objective_2',
								'label' => '??? 2',
								'name'  => 'program_3_objective_2',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_3_objective_3',
								'label' => '??? 3',
								'name'  => 'program_3_objective_3',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_3_objective_4',
								'label' => '??? 4',
								'name'  => 'program_3_objective_4',
								'type'  => 'text',
							),
						),
					),
					array(
						'key'   => 'field_program_4',
						'label' => '?????? 4',
						'name'  => 'program_4',
						'type'  => 'group',
						'sub_fields' => array(
							array(
								'key'   => 'field_program_4_title',
								'label' => '???????',
								'name'  => 'program_4_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_4_description',
								'label' => '?????',
								'name'  => 'program_4_description',
								'type'  => 'textarea',
							),
							array(
								'key'   => 'field_program_4_beneficiaries',
								'label' => '??????????',
								'name'  => 'program_4_beneficiaries',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_4_duration',
								'label' => '?????',
								'name'  => 'program_4_duration',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_4_location',
								'label' => '??????',
								'name'  => 'program_4_location',
								'type'  => 'text',
							),
							array(
								'key'            => 'field_program_4_image',
								'label'          => 'صورة البرنامج',
								'name'           => 'program_4_image',
								'type'           => 'image',
								'return_format'  => 'url',
								'preview_size'   => 'medium',
								'library'        => 'all',
							),
							array(
								'key'   => 'field_program_4_objective_1',
								'label' => '??? 1',
								'name'  => 'program_4_objective_1',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_4_objective_2',
								'label' => '??? 2',
								'name'  => 'program_4_objective_2',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_4_objective_3',
								'label' => '??? 3',
								'name'  => 'program_4_objective_3',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_4_objective_4',
								'label' => '??? 4',
								'name'  => 'program_4_objective_4',
								'type'  => 'text',
							),
						),
					),
					array(
						'key'   => 'field_program_5',
						'label' => '?????? 5',
						'name'  => 'program_5',
						'type'  => 'group',
						'sub_fields' => array(
							array(
								'key'   => 'field_program_5_title',
								'label' => '???????',
								'name'  => 'program_5_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_5_description',
								'label' => '?????',
								'name'  => 'program_5_description',
								'type'  => 'textarea',
							),
							array(
								'key'   => 'field_program_5_beneficiaries',
								'label' => '??????????',
								'name'  => 'program_5_beneficiaries',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_5_duration',
								'label' => '?????',
								'name'  => 'program_5_duration',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_5_location',
								'label' => '??????',
								'name'  => 'program_5_location',
								'type'  => 'text',
							),
							array(
								'key'            => 'field_program_5_image',
								'label'          => 'صورة البرنامج',
								'name'           => 'program_5_image',
								'type'           => 'image',
								'return_format'  => 'url',
								'preview_size'   => 'medium',
								'library'        => 'all',
							),
							array(
								'key'   => 'field_program_5_objective_1',
								'label' => '??? 1',
								'name'  => 'program_5_objective_1',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_5_objective_2',
								'label' => '??? 2',
								'name'  => 'program_5_objective_2',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_5_objective_3',
								'label' => '??? 3',
								'name'  => 'program_5_objective_3',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_5_objective_4',
								'label' => '??? 4',
								'name'  => 'program_5_objective_4',
								'type'  => 'text',
							),
						),
					),
					array(
						'key'   => 'field_program_6',
						'label' => '?????? 6',
						'name'  => 'program_6',
						'type'  => 'group',
						'sub_fields' => array(
							array(
								'key'   => 'field_program_6_title',
								'label' => '???????',
								'name'  => 'program_6_title',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_6_description',
								'label' => '?????',
								'name'  => 'program_6_description',
								'type'  => 'textarea',
							),
							array(
								'key'   => 'field_program_6_beneficiaries',
								'label' => '??????????',
								'name'  => 'program_6_beneficiaries',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_6_duration',
								'label' => '?????',
								'name'  => 'program_6_duration',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_6_location',
								'label' => '??????',
								'name'  => 'program_6_location',
								'type'  => 'text',
							),
							array(
								'key'            => 'field_program_6_image',
								'label'          => 'صورة البرنامج',
								'name'           => 'program_6_image',
								'type'           => 'image',
								'return_format'  => 'url',
								'preview_size'   => 'medium',
								'library'        => 'all',
							),
							array(
								'key'   => 'field_program_6_objective_1',
								'label' => '??? 1',
								'name'  => 'program_6_objective_1',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_6_objective_2',
								'label' => '??? 2',
								'name'  => 'program_6_objective_2',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_6_objective_3',
								'label' => '??? 3',
								'name'  => 'program_6_objective_3',
								'type'  => 'text',
							),
							array(
								'key'   => 'field_program_6_objective_4',
								'label' => '??? 4',
								'name'  => 'program_6_objective_4',
								'type'  => 'text',
							),
						),
					),
				),
			),
			),
			'location' => array(
				array(
					array(
						'param'    => 'page',
						'operator' => '==',
						'value'    => $page_id,
					),
				),
			),
			'position' => 'acf_after_title',
			'style'    => 'seamless',
		)
	);
}
add_action( 'acf/init', 'astra_mohcine_register_acf_fields' );
